### ISSUE TITLE
Is is possible to get cad files?

### ISSUE THREAD

**Issue by vitormhenrique** [UnexpectedMaker/manual_pnp_turntable#1]
This is an awesome design! thanks for sharing!
Would you mind sharing the cad designs for it (step files for example) ? (instead of the STL ones) there are a couple things that I think would be nice, and editing STL's are never too fun...

Thanks!

**Comment by UnexpectedMaker** [comment]
Not suer if you noticed but I added STEP files a while ago :)

**Comment by vitormhenrique** [comment]
I did! Thank you very much!
