### ISSUE TITLE
Bigger boxes?

### ISSUE THREAD

**Issue by taposk** [UnexpectedMaker/manual_pnp_turntable#5]
Hi!
Is it possible to get a version with a few "bigger" boxes (2x or 3x the size).
I'm using some rather "big" components and the little boxes get filled quite fast. But my components still get trough the small hatch so it would work I guess. 
I tried "cutting" the boxes with pliers but it's not as "nice" than if it was a proper one... 
Thank you!

**Comment by TadeasPilar** [comment]
Already solved here: https://github.com/UnexpectedMaker/manual_pnp_turntable/tree/master/TadeasPilar_upgrades
